#!/bin/csh

# first configure the makefile

echo '# Makefile routine.' > makefile.new
echo '' >> makefile.new
echo 'MCFMHOME        = '`pwd` >> makefile.new
echo 'MYHOME          = '`pwd` >> makefile.new
tail +5 makefile >> makefile.new
mv makefile.new makefile

cd Doc
latex mcfm
latex mcfm

echo ''
echo 'Installation complete. You may now compile MCFM by running make.'
