      SUBROUTINE SGG_VEEPBBBMUMV(P1,ANS)
C  
C FUNCTION GENERATED BY MADGRAPH
C RETURNS AMPLITUDE SQUARED SUMMED/AVG OVER COLORS
C AND HELICITIES
C FOR THE POINT IN PHASE SPACE P(0:3,NEXTERNAL)
C  
C FOR PROCESS : g g -> ve e+ b b~ mu- vm~ g  
C  
C Crossing   1 is g g -> ve e+ b b~ mu- vm~ g  
      IMPLICIT NONE
C  
C CONSTANTS
C  
      INTEGER    NEXTERNAL,   NCOMB,     NCROSS         
      PARAMETER (NEXTERNAL=9, NCOMB=512, NCROSS=  1)
      INTEGER    THEL
      PARAMETER (THEL=NCOMB*NCROSS)
C  
C ARGUMENTS 
C  
      REAL*8 P1(0:3,NEXTERNAL),ANS(NCROSS)
C  
C LOCAL VARIABLES 
C  
      INTEGER NHEL(NEXTERNAL,NCOMB),NTRY
      REAL*8 T, P(0:3,NEXTERNAL)
      REAL*8 GG_VEEPBBBMUMV
      INTEGER IHEL,IDEN(NCROSS),IC(NEXTERNAL,NCROSS)
      INTEGER IPROC,JC(NEXTERNAL)
      LOGICAL GOODHEL(NCOMB,NCROSS)
      DATA GOODHEL/THEL*.FALSE./
      DATA NTRY/0/
      DATA (NHEL(IHEL,  1),IHEL=1,9) / -1, -1, -1, -1, -1, -1, -1, -1, -1/
      DATA (NHEL(IHEL,  2),IHEL=1,9) / -1, -1, -1, -1, -1, -1, -1, -1,  1/
      DATA (NHEL(IHEL,  3),IHEL=1,9) / -1, -1, -1, -1, -1, -1, -1,  1, -1/
      DATA (NHEL(IHEL,  4),IHEL=1,9) / -1, -1, -1, -1, -1, -1, -1,  1,  1/
      DATA (NHEL(IHEL,  5),IHEL=1,9) / -1, -1, -1, -1, -1, -1,  1, -1, -1/
      DATA (NHEL(IHEL,  6),IHEL=1,9) / -1, -1, -1, -1, -1, -1,  1, -1,  1/
      DATA (NHEL(IHEL,  7),IHEL=1,9) / -1, -1, -1, -1, -1, -1,  1,  1, -1/
      DATA (NHEL(IHEL,  8),IHEL=1,9) / -1, -1, -1, -1, -1, -1,  1,  1,  1/
      DATA (NHEL(IHEL,  9),IHEL=1,9) / -1, -1, -1, -1, -1,  1, -1, -1, -1/
      DATA (NHEL(IHEL, 10),IHEL=1,9) / -1, -1, -1, -1, -1,  1, -1, -1,  1/
      DATA (NHEL(IHEL, 11),IHEL=1,9) / -1, -1, -1, -1, -1,  1, -1,  1, -1/
      DATA (NHEL(IHEL, 12),IHEL=1,9) / -1, -1, -1, -1, -1,  1, -1,  1,  1/
      DATA (NHEL(IHEL, 13),IHEL=1,9) / -1, -1, -1, -1, -1,  1,  1, -1, -1/
      DATA (NHEL(IHEL, 14),IHEL=1,9) / -1, -1, -1, -1, -1,  1,  1, -1,  1/
      DATA (NHEL(IHEL, 15),IHEL=1,9) / -1, -1, -1, -1, -1,  1,  1,  1, -1/
      DATA (NHEL(IHEL, 16),IHEL=1,9) / -1, -1, -1, -1, -1,  1,  1,  1,  1/
      DATA (NHEL(IHEL, 17),IHEL=1,9) / -1, -1, -1, -1,  1, -1, -1, -1, -1/
      DATA (NHEL(IHEL, 18),IHEL=1,9) / -1, -1, -1, -1,  1, -1, -1, -1,  1/
      DATA (NHEL(IHEL, 19),IHEL=1,9) / -1, -1, -1, -1,  1, -1, -1,  1, -1/
      DATA (NHEL(IHEL, 20),IHEL=1,9) / -1, -1, -1, -1,  1, -1, -1,  1,  1/
      DATA (NHEL(IHEL, 21),IHEL=1,9) / -1, -1, -1, -1,  1, -1,  1, -1, -1/
      DATA (NHEL(IHEL, 22),IHEL=1,9) / -1, -1, -1, -1,  1, -1,  1, -1,  1/
      DATA (NHEL(IHEL, 23),IHEL=1,9) / -1, -1, -1, -1,  1, -1,  1,  1, -1/
      DATA (NHEL(IHEL, 24),IHEL=1,9) / -1, -1, -1, -1,  1, -1,  1,  1,  1/
      DATA (NHEL(IHEL, 25),IHEL=1,9) / -1, -1, -1, -1,  1,  1, -1, -1, -1/
      DATA (NHEL(IHEL, 26),IHEL=1,9) / -1, -1, -1, -1,  1,  1, -1, -1,  1/
      DATA (NHEL(IHEL, 27),IHEL=1,9) / -1, -1, -1, -1,  1,  1, -1,  1, -1/
      DATA (NHEL(IHEL, 28),IHEL=1,9) / -1, -1, -1, -1,  1,  1, -1,  1,  1/
      DATA (NHEL(IHEL, 29),IHEL=1,9) / -1, -1, -1, -1,  1,  1,  1, -1, -1/
      DATA (NHEL(IHEL, 30),IHEL=1,9) / -1, -1, -1, -1,  1,  1,  1, -1,  1/
      DATA (NHEL(IHEL, 31),IHEL=1,9) / -1, -1, -1, -1,  1,  1,  1,  1, -1/
      DATA (NHEL(IHEL, 32),IHEL=1,9) / -1, -1, -1, -1,  1,  1,  1,  1,  1/
      DATA (NHEL(IHEL, 33),IHEL=1,9) / -1, -1, -1,  1, -1, -1, -1, -1, -1/
      DATA (NHEL(IHEL, 34),IHEL=1,9) / -1, -1, -1,  1, -1, -1, -1, -1,  1/
      DATA (NHEL(IHEL, 35),IHEL=1,9) / -1, -1, -1,  1, -1, -1, -1,  1, -1/
      DATA (NHEL(IHEL, 36),IHEL=1,9) / -1, -1, -1,  1, -1, -1, -1,  1,  1/
      DATA (NHEL(IHEL, 37),IHEL=1,9) / -1, -1, -1,  1, -1, -1,  1, -1, -1/
      DATA (NHEL(IHEL, 38),IHEL=1,9) / -1, -1, -1,  1, -1, -1,  1, -1,  1/
      DATA (NHEL(IHEL, 39),IHEL=1,9) / -1, -1, -1,  1, -1, -1,  1,  1, -1/
      DATA (NHEL(IHEL, 40),IHEL=1,9) / -1, -1, -1,  1, -1, -1,  1,  1,  1/
      DATA (NHEL(IHEL, 41),IHEL=1,9) / -1, -1, -1,  1, -1,  1, -1, -1, -1/
      DATA (NHEL(IHEL, 42),IHEL=1,9) / -1, -1, -1,  1, -1,  1, -1, -1,  1/
      DATA (NHEL(IHEL, 43),IHEL=1,9) / -1, -1, -1,  1, -1,  1, -1,  1, -1/
      DATA (NHEL(IHEL, 44),IHEL=1,9) / -1, -1, -1,  1, -1,  1, -1,  1,  1/
      DATA (NHEL(IHEL, 45),IHEL=1,9) / -1, -1, -1,  1, -1,  1,  1, -1, -1/
      DATA (NHEL(IHEL, 46),IHEL=1,9) / -1, -1, -1,  1, -1,  1,  1, -1,  1/
      DATA (NHEL(IHEL, 47),IHEL=1,9) / -1, -1, -1,  1, -1,  1,  1,  1, -1/
      DATA (NHEL(IHEL, 48),IHEL=1,9) / -1, -1, -1,  1, -1,  1,  1,  1,  1/
      DATA (NHEL(IHEL, 49),IHEL=1,9) / -1, -1, -1,  1,  1, -1, -1, -1, -1/
      DATA (NHEL(IHEL, 50),IHEL=1,9) / -1, -1, -1,  1,  1, -1, -1, -1,  1/
      DATA (NHEL(IHEL, 51),IHEL=1,9) / -1, -1, -1,  1,  1, -1, -1,  1, -1/
      DATA (NHEL(IHEL, 52),IHEL=1,9) / -1, -1, -1,  1,  1, -1, -1,  1,  1/
      DATA (NHEL(IHEL, 53),IHEL=1,9) / -1, -1, -1,  1,  1, -1,  1, -1, -1/
      DATA (NHEL(IHEL, 54),IHEL=1,9) / -1, -1, -1,  1,  1, -1,  1, -1,  1/
      DATA (NHEL(IHEL, 55),IHEL=1,9) / -1, -1, -1,  1,  1, -1,  1,  1, -1/
      DATA (NHEL(IHEL, 56),IHEL=1,9) / -1, -1, -1,  1,  1, -1,  1,  1,  1/
      DATA (NHEL(IHEL, 57),IHEL=1,9) / -1, -1, -1,  1,  1,  1, -1, -1, -1/
      DATA (NHEL(IHEL, 58),IHEL=1,9) / -1, -1, -1,  1,  1,  1, -1, -1,  1/
      DATA (NHEL(IHEL, 59),IHEL=1,9) / -1, -1, -1,  1,  1,  1, -1,  1, -1/
      DATA (NHEL(IHEL, 60),IHEL=1,9) / -1, -1, -1,  1,  1,  1, -1,  1,  1/
      DATA (NHEL(IHEL, 61),IHEL=1,9) / -1, -1, -1,  1,  1,  1,  1, -1, -1/
      DATA (NHEL(IHEL, 62),IHEL=1,9) / -1, -1, -1,  1,  1,  1,  1, -1,  1/
      DATA (NHEL(IHEL, 63),IHEL=1,9) / -1, -1, -1,  1,  1,  1,  1,  1, -1/
      DATA (NHEL(IHEL, 64),IHEL=1,9) / -1, -1, -1,  1,  1,  1,  1,  1,  1/
      DATA (NHEL(IHEL, 65),IHEL=1,9) / -1, -1,  1, -1, -1, -1, -1, -1, -1/
      DATA (NHEL(IHEL, 66),IHEL=1,9) / -1, -1,  1, -1, -1, -1, -1, -1,  1/
      DATA (NHEL(IHEL, 67),IHEL=1,9) / -1, -1,  1, -1, -1, -1, -1,  1, -1/
      DATA (NHEL(IHEL, 68),IHEL=1,9) / -1, -1,  1, -1, -1, -1, -1,  1,  1/
      DATA (NHEL(IHEL, 69),IHEL=1,9) / -1, -1,  1, -1, -1, -1,  1, -1, -1/
      DATA (NHEL(IHEL, 70),IHEL=1,9) / -1, -1,  1, -1, -1, -1,  1, -1,  1/
      DATA (NHEL(IHEL, 71),IHEL=1,9) / -1, -1,  1, -1, -1, -1,  1,  1, -1/
      DATA (NHEL(IHEL, 72),IHEL=1,9) / -1, -1,  1, -1, -1, -1,  1,  1,  1/
      DATA (NHEL(IHEL, 73),IHEL=1,9) / -1, -1,  1, -1, -1,  1, -1, -1, -1/
      DATA (NHEL(IHEL, 74),IHEL=1,9) / -1, -1,  1, -1, -1,  1, -1, -1,  1/
      DATA (NHEL(IHEL, 75),IHEL=1,9) / -1, -1,  1, -1, -1,  1, -1,  1, -1/
      DATA (NHEL(IHEL, 76),IHEL=1,9) / -1, -1,  1, -1, -1,  1, -1,  1,  1/
      DATA (NHEL(IHEL, 77),IHEL=1,9) / -1, -1,  1, -1, -1,  1,  1, -1, -1/
      DATA (NHEL(IHEL, 78),IHEL=1,9) / -1, -1,  1, -1, -1,  1,  1, -1,  1/
      DATA (NHEL(IHEL, 79),IHEL=1,9) / -1, -1,  1, -1, -1,  1,  1,  1, -1/
      DATA (NHEL(IHEL, 80),IHEL=1,9) / -1, -1,  1, -1, -1,  1,  1,  1,  1/
      DATA (NHEL(IHEL, 81),IHEL=1,9) / -1, -1,  1, -1,  1, -1, -1, -1, -1/
      DATA (NHEL(IHEL, 82),IHEL=1,9) / -1, -1,  1, -1,  1, -1, -1, -1,  1/
      DATA (NHEL(IHEL, 83),IHEL=1,9) / -1, -1,  1, -1,  1, -1, -1,  1, -1/
      DATA (NHEL(IHEL, 84),IHEL=1,9) / -1, -1,  1, -1,  1, -1, -1,  1,  1/
      DATA (NHEL(IHEL, 85),IHEL=1,9) / -1, -1,  1, -1,  1, -1,  1, -1, -1/
      DATA (NHEL(IHEL, 86),IHEL=1,9) / -1, -1,  1, -1,  1, -1,  1, -1,  1/
      DATA (NHEL(IHEL, 87),IHEL=1,9) / -1, -1,  1, -1,  1, -1,  1,  1, -1/
      DATA (NHEL(IHEL, 88),IHEL=1,9) / -1, -1,  1, -1,  1, -1,  1,  1,  1/
      DATA (NHEL(IHEL, 89),IHEL=1,9) / -1, -1,  1, -1,  1,  1, -1, -1, -1/
      DATA (NHEL(IHEL, 90),IHEL=1,9) / -1, -1,  1, -1,  1,  1, -1, -1,  1/
      DATA (NHEL(IHEL, 91),IHEL=1,9) / -1, -1,  1, -1,  1,  1, -1,  1, -1/
      DATA (NHEL(IHEL, 92),IHEL=1,9) / -1, -1,  1, -1,  1,  1, -1,  1,  1/
      DATA (NHEL(IHEL, 93),IHEL=1,9) / -1, -1,  1, -1,  1,  1,  1, -1, -1/
      DATA (NHEL(IHEL, 94),IHEL=1,9) / -1, -1,  1, -1,  1,  1,  1, -1,  1/
      DATA (NHEL(IHEL, 95),IHEL=1,9) / -1, -1,  1, -1,  1,  1,  1,  1, -1/
      DATA (NHEL(IHEL, 96),IHEL=1,9) / -1, -1,  1, -1,  1,  1,  1,  1,  1/
      DATA (NHEL(IHEL, 97),IHEL=1,9) / -1, -1,  1,  1, -1, -1, -1, -1, -1/
      DATA (NHEL(IHEL, 98),IHEL=1,9) / -1, -1,  1,  1, -1, -1, -1, -1,  1/
      DATA (NHEL(IHEL, 99),IHEL=1,9) / -1, -1,  1,  1, -1, -1, -1,  1, -1/
      DATA (NHEL(IHEL,100),IHEL=1,9) / -1, -1,  1,  1, -1, -1, -1,  1,  1/
      DATA (NHEL(IHEL,101),IHEL=1,9) / -1, -1,  1,  1, -1, -1,  1, -1, -1/
      DATA (NHEL(IHEL,102),IHEL=1,9) / -1, -1,  1,  1, -1, -1,  1, -1,  1/
      DATA (NHEL(IHEL,103),IHEL=1,9) / -1, -1,  1,  1, -1, -1,  1,  1, -1/
      DATA (NHEL(IHEL,104),IHEL=1,9) / -1, -1,  1,  1, -1, -1,  1,  1,  1/
      DATA (NHEL(IHEL,105),IHEL=1,9) / -1, -1,  1,  1, -1,  1, -1, -1, -1/
      DATA (NHEL(IHEL,106),IHEL=1,9) / -1, -1,  1,  1, -1,  1, -1, -1,  1/
      DATA (NHEL(IHEL,107),IHEL=1,9) / -1, -1,  1,  1, -1,  1, -1,  1, -1/
      DATA (NHEL(IHEL,108),IHEL=1,9) / -1, -1,  1,  1, -1,  1, -1,  1,  1/
      DATA (NHEL(IHEL,109),IHEL=1,9) / -1, -1,  1,  1, -1,  1,  1, -1, -1/
      DATA (NHEL(IHEL,110),IHEL=1,9) / -1, -1,  1,  1, -1,  1,  1, -1,  1/
      DATA (NHEL(IHEL,111),IHEL=1,9) / -1, -1,  1,  1, -1,  1,  1,  1, -1/
      DATA (NHEL(IHEL,112),IHEL=1,9) / -1, -1,  1,  1, -1,  1,  1,  1,  1/
      DATA (NHEL(IHEL,113),IHEL=1,9) / -1, -1,  1,  1,  1, -1, -1, -1, -1/
      DATA (NHEL(IHEL,114),IHEL=1,9) / -1, -1,  1,  1,  1, -1, -1, -1,  1/
      DATA (NHEL(IHEL,115),IHEL=1,9) / -1, -1,  1,  1,  1, -1, -1,  1, -1/
      DATA (NHEL(IHEL,116),IHEL=1,9) / -1, -1,  1,  1,  1, -1, -1,  1,  1/
      DATA (NHEL(IHEL,117),IHEL=1,9) / -1, -1,  1,  1,  1, -1,  1, -1, -1/
      DATA (NHEL(IHEL,118),IHEL=1,9) / -1, -1,  1,  1,  1, -1,  1, -1,  1/
      DATA (NHEL(IHEL,119),IHEL=1,9) / -1, -1,  1,  1,  1, -1,  1,  1, -1/
      DATA (NHEL(IHEL,120),IHEL=1,9) / -1, -1,  1,  1,  1, -1,  1,  1,  1/
      DATA (NHEL(IHEL,121),IHEL=1,9) / -1, -1,  1,  1,  1,  1, -1, -1, -1/
      DATA (NHEL(IHEL,122),IHEL=1,9) / -1, -1,  1,  1,  1,  1, -1, -1,  1/
      DATA (NHEL(IHEL,123),IHEL=1,9) / -1, -1,  1,  1,  1,  1, -1,  1, -1/
      DATA (NHEL(IHEL,124),IHEL=1,9) / -1, -1,  1,  1,  1,  1, -1,  1,  1/
      DATA (NHEL(IHEL,125),IHEL=1,9) / -1, -1,  1,  1,  1,  1,  1, -1, -1/
      DATA (NHEL(IHEL,126),IHEL=1,9) / -1, -1,  1,  1,  1,  1,  1, -1,  1/
      DATA (NHEL(IHEL,127),IHEL=1,9) / -1, -1,  1,  1,  1,  1,  1,  1, -1/
      DATA (NHEL(IHEL,128),IHEL=1,9) / -1, -1,  1,  1,  1,  1,  1,  1,  1/
      DATA (NHEL(IHEL,129),IHEL=1,9) / -1,  1, -1, -1, -1, -1, -1, -1, -1/
      DATA (NHEL(IHEL,130),IHEL=1,9) / -1,  1, -1, -1, -1, -1, -1, -1,  1/
      DATA (NHEL(IHEL,131),IHEL=1,9) / -1,  1, -1, -1, -1, -1, -1,  1, -1/
      DATA (NHEL(IHEL,132),IHEL=1,9) / -1,  1, -1, -1, -1, -1, -1,  1,  1/
      DATA (NHEL(IHEL,133),IHEL=1,9) / -1,  1, -1, -1, -1, -1,  1, -1, -1/
      DATA (NHEL(IHEL,134),IHEL=1,9) / -1,  1, -1, -1, -1, -1,  1, -1,  1/
      DATA (NHEL(IHEL,135),IHEL=1,9) / -1,  1, -1, -1, -1, -1,  1,  1, -1/
      DATA (NHEL(IHEL,136),IHEL=1,9) / -1,  1, -1, -1, -1, -1,  1,  1,  1/
      DATA (NHEL(IHEL,137),IHEL=1,9) / -1,  1, -1, -1, -1,  1, -1, -1, -1/
      DATA (NHEL(IHEL,138),IHEL=1,9) / -1,  1, -1, -1, -1,  1, -1, -1,  1/
      DATA (NHEL(IHEL,139),IHEL=1,9) / -1,  1, -1, -1, -1,  1, -1,  1, -1/
      DATA (NHEL(IHEL,140),IHEL=1,9) / -1,  1, -1, -1, -1,  1, -1,  1,  1/
      DATA (NHEL(IHEL,141),IHEL=1,9) / -1,  1, -1, -1, -1,  1,  1, -1, -1/
      DATA (NHEL(IHEL,142),IHEL=1,9) / -1,  1, -1, -1, -1,  1,  1, -1,  1/
      DATA (NHEL(IHEL,143),IHEL=1,9) / -1,  1, -1, -1, -1,  1,  1,  1, -1/
      DATA (NHEL(IHEL,144),IHEL=1,9) / -1,  1, -1, -1, -1,  1,  1,  1,  1/
      DATA (NHEL(IHEL,145),IHEL=1,9) / -1,  1, -1, -1,  1, -1, -1, -1, -1/
      DATA (NHEL(IHEL,146),IHEL=1,9) / -1,  1, -1, -1,  1, -1, -1, -1,  1/
      DATA (NHEL(IHEL,147),IHEL=1,9) / -1,  1, -1, -1,  1, -1, -1,  1, -1/
      DATA (NHEL(IHEL,148),IHEL=1,9) / -1,  1, -1, -1,  1, -1, -1,  1,  1/
      DATA (NHEL(IHEL,149),IHEL=1,9) / -1,  1, -1, -1,  1, -1,  1, -1, -1/
      DATA (NHEL(IHEL,150),IHEL=1,9) / -1,  1, -1, -1,  1, -1,  1, -1,  1/
      DATA (NHEL(IHEL,151),IHEL=1,9) / -1,  1, -1, -1,  1, -1,  1,  1, -1/
      DATA (NHEL(IHEL,152),IHEL=1,9) / -1,  1, -1, -1,  1, -1,  1,  1,  1/
      DATA (NHEL(IHEL,153),IHEL=1,9) / -1,  1, -1, -1,  1,  1, -1, -1, -1/
      DATA (NHEL(IHEL,154),IHEL=1,9) / -1,  1, -1, -1,  1,  1, -1, -1,  1/
      DATA (NHEL(IHEL,155),IHEL=1,9) / -1,  1, -1, -1,  1,  1, -1,  1, -1/
      DATA (NHEL(IHEL,156),IHEL=1,9) / -1,  1, -1, -1,  1,  1, -1,  1,  1/
      DATA (NHEL(IHEL,157),IHEL=1,9) / -1,  1, -1, -1,  1,  1,  1, -1, -1/
      DATA (NHEL(IHEL,158),IHEL=1,9) / -1,  1, -1, -1,  1,  1,  1, -1,  1/
      DATA (NHEL(IHEL,159),IHEL=1,9) / -1,  1, -1, -1,  1,  1,  1,  1, -1/
      DATA (NHEL(IHEL,160),IHEL=1,9) / -1,  1, -1, -1,  1,  1,  1,  1,  1/
      DATA (NHEL(IHEL,161),IHEL=1,9) / -1,  1, -1,  1, -1, -1, -1, -1, -1/
      DATA (NHEL(IHEL,162),IHEL=1,9) / -1,  1, -1,  1, -1, -1, -1, -1,  1/
      DATA (NHEL(IHEL,163),IHEL=1,9) / -1,  1, -1,  1, -1, -1, -1,  1, -1/
      DATA (NHEL(IHEL,164),IHEL=1,9) / -1,  1, -1,  1, -1, -1, -1,  1,  1/
      DATA (NHEL(IHEL,165),IHEL=1,9) / -1,  1, -1,  1, -1, -1,  1, -1, -1/
      DATA (NHEL(IHEL,166),IHEL=1,9) / -1,  1, -1,  1, -1, -1,  1, -1,  1/
      DATA (NHEL(IHEL,167),IHEL=1,9) / -1,  1, -1,  1, -1, -1,  1,  1, -1/
      DATA (NHEL(IHEL,168),IHEL=1,9) / -1,  1, -1,  1, -1, -1,  1,  1,  1/
      DATA (NHEL(IHEL,169),IHEL=1,9) / -1,  1, -1,  1, -1,  1, -1, -1, -1/
      DATA (NHEL(IHEL,170),IHEL=1,9) / -1,  1, -1,  1, -1,  1, -1, -1,  1/
      DATA (NHEL(IHEL,171),IHEL=1,9) / -1,  1, -1,  1, -1,  1, -1,  1, -1/
      DATA (NHEL(IHEL,172),IHEL=1,9) / -1,  1, -1,  1, -1,  1, -1,  1,  1/
      DATA (NHEL(IHEL,173),IHEL=1,9) / -1,  1, -1,  1, -1,  1,  1, -1, -1/
      DATA (NHEL(IHEL,174),IHEL=1,9) / -1,  1, -1,  1, -1,  1,  1, -1,  1/
      DATA (NHEL(IHEL,175),IHEL=1,9) / -1,  1, -1,  1, -1,  1,  1,  1, -1/
      DATA (NHEL(IHEL,176),IHEL=1,9) / -1,  1, -1,  1, -1,  1,  1,  1,  1/
      DATA (NHEL(IHEL,177),IHEL=1,9) / -1,  1, -1,  1,  1, -1, -1, -1, -1/
      DATA (NHEL(IHEL,178),IHEL=1,9) / -1,  1, -1,  1,  1, -1, -1, -1,  1/
      DATA (NHEL(IHEL,179),IHEL=1,9) / -1,  1, -1,  1,  1, -1, -1,  1, -1/
      DATA (NHEL(IHEL,180),IHEL=1,9) / -1,  1, -1,  1,  1, -1, -1,  1,  1/
      DATA (NHEL(IHEL,181),IHEL=1,9) / -1,  1, -1,  1,  1, -1,  1, -1, -1/
      DATA (NHEL(IHEL,182),IHEL=1,9) / -1,  1, -1,  1,  1, -1,  1, -1,  1/
      DATA (NHEL(IHEL,183),IHEL=1,9) / -1,  1, -1,  1,  1, -1,  1,  1, -1/
      DATA (NHEL(IHEL,184),IHEL=1,9) / -1,  1, -1,  1,  1, -1,  1,  1,  1/
      DATA (NHEL(IHEL,185),IHEL=1,9) / -1,  1, -1,  1,  1,  1, -1, -1, -1/
      DATA (NHEL(IHEL,186),IHEL=1,9) / -1,  1, -1,  1,  1,  1, -1, -1,  1/
      DATA (NHEL(IHEL,187),IHEL=1,9) / -1,  1, -1,  1,  1,  1, -1,  1, -1/
      DATA (NHEL(IHEL,188),IHEL=1,9) / -1,  1, -1,  1,  1,  1, -1,  1,  1/
      DATA (NHEL(IHEL,189),IHEL=1,9) / -1,  1, -1,  1,  1,  1,  1, -1, -1/
      DATA (NHEL(IHEL,190),IHEL=1,9) / -1,  1, -1,  1,  1,  1,  1, -1,  1/
      DATA (NHEL(IHEL,191),IHEL=1,9) / -1,  1, -1,  1,  1,  1,  1,  1, -1/
      DATA (NHEL(IHEL,192),IHEL=1,9) / -1,  1, -1,  1,  1,  1,  1,  1,  1/
      DATA (NHEL(IHEL,193),IHEL=1,9) / -1,  1,  1, -1, -1, -1, -1, -1, -1/
      DATA (NHEL(IHEL,194),IHEL=1,9) / -1,  1,  1, -1, -1, -1, -1, -1,  1/
      DATA (NHEL(IHEL,195),IHEL=1,9) / -1,  1,  1, -1, -1, -1, -1,  1, -1/
      DATA (NHEL(IHEL,196),IHEL=1,9) / -1,  1,  1, -1, -1, -1, -1,  1,  1/
      DATA (NHEL(IHEL,197),IHEL=1,9) / -1,  1,  1, -1, -1, -1,  1, -1, -1/
      DATA (NHEL(IHEL,198),IHEL=1,9) / -1,  1,  1, -1, -1, -1,  1, -1,  1/
      DATA (NHEL(IHEL,199),IHEL=1,9) / -1,  1,  1, -1, -1, -1,  1,  1, -1/
      DATA (NHEL(IHEL,200),IHEL=1,9) / -1,  1,  1, -1, -1, -1,  1,  1,  1/
      DATA (NHEL(IHEL,201),IHEL=1,9) / -1,  1,  1, -1, -1,  1, -1, -1, -1/
      DATA (NHEL(IHEL,202),IHEL=1,9) / -1,  1,  1, -1, -1,  1, -1, -1,  1/
      DATA (NHEL(IHEL,203),IHEL=1,9) / -1,  1,  1, -1, -1,  1, -1,  1, -1/
      DATA (NHEL(IHEL,204),IHEL=1,9) / -1,  1,  1, -1, -1,  1, -1,  1,  1/
      DATA (NHEL(IHEL,205),IHEL=1,9) / -1,  1,  1, -1, -1,  1,  1, -1, -1/
      DATA (NHEL(IHEL,206),IHEL=1,9) / -1,  1,  1, -1, -1,  1,  1, -1,  1/
      DATA (NHEL(IHEL,207),IHEL=1,9) / -1,  1,  1, -1, -1,  1,  1,  1, -1/
      DATA (NHEL(IHEL,208),IHEL=1,9) / -1,  1,  1, -1, -1,  1,  1,  1,  1/
      DATA (NHEL(IHEL,209),IHEL=1,9) / -1,  1,  1, -1,  1, -1, -1, -1, -1/
      DATA (NHEL(IHEL,210),IHEL=1,9) / -1,  1,  1, -1,  1, -1, -1, -1,  1/
      DATA (NHEL(IHEL,211),IHEL=1,9) / -1,  1,  1, -1,  1, -1, -1,  1, -1/
      DATA (NHEL(IHEL,212),IHEL=1,9) / -1,  1,  1, -1,  1, -1, -1,  1,  1/
      DATA (NHEL(IHEL,213),IHEL=1,9) / -1,  1,  1, -1,  1, -1,  1, -1, -1/
      DATA (NHEL(IHEL,214),IHEL=1,9) / -1,  1,  1, -1,  1, -1,  1, -1,  1/
      DATA (NHEL(IHEL,215),IHEL=1,9) / -1,  1,  1, -1,  1, -1,  1,  1, -1/
      DATA (NHEL(IHEL,216),IHEL=1,9) / -1,  1,  1, -1,  1, -1,  1,  1,  1/
      DATA (NHEL(IHEL,217),IHEL=1,9) / -1,  1,  1, -1,  1,  1, -1, -1, -1/
      DATA (NHEL(IHEL,218),IHEL=1,9) / -1,  1,  1, -1,  1,  1, -1, -1,  1/
      DATA (NHEL(IHEL,219),IHEL=1,9) / -1,  1,  1, -1,  1,  1, -1,  1, -1/
      DATA (NHEL(IHEL,220),IHEL=1,9) / -1,  1,  1, -1,  1,  1, -1,  1,  1/
      DATA (NHEL(IHEL,221),IHEL=1,9) / -1,  1,  1, -1,  1,  1,  1, -1, -1/
      DATA (NHEL(IHEL,222),IHEL=1,9) / -1,  1,  1, -1,  1,  1,  1, -1,  1/
      DATA (NHEL(IHEL,223),IHEL=1,9) / -1,  1,  1, -1,  1,  1,  1,  1, -1/
      DATA (NHEL(IHEL,224),IHEL=1,9) / -1,  1,  1, -1,  1,  1,  1,  1,  1/
      DATA (NHEL(IHEL,225),IHEL=1,9) / -1,  1,  1,  1, -1, -1, -1, -1, -1/
      DATA (NHEL(IHEL,226),IHEL=1,9) / -1,  1,  1,  1, -1, -1, -1, -1,  1/
      DATA (NHEL(IHEL,227),IHEL=1,9) / -1,  1,  1,  1, -1, -1, -1,  1, -1/
      DATA (NHEL(IHEL,228),IHEL=1,9) / -1,  1,  1,  1, -1, -1, -1,  1,  1/
      DATA (NHEL(IHEL,229),IHEL=1,9) / -1,  1,  1,  1, -1, -1,  1, -1, -1/
      DATA (NHEL(IHEL,230),IHEL=1,9) / -1,  1,  1,  1, -1, -1,  1, -1,  1/
      DATA (NHEL(IHEL,231),IHEL=1,9) / -1,  1,  1,  1, -1, -1,  1,  1, -1/
      DATA (NHEL(IHEL,232),IHEL=1,9) / -1,  1,  1,  1, -1, -1,  1,  1,  1/
      DATA (NHEL(IHEL,233),IHEL=1,9) / -1,  1,  1,  1, -1,  1, -1, -1, -1/
      DATA (NHEL(IHEL,234),IHEL=1,9) / -1,  1,  1,  1, -1,  1, -1, -1,  1/
      DATA (NHEL(IHEL,235),IHEL=1,9) / -1,  1,  1,  1, -1,  1, -1,  1, -1/
      DATA (NHEL(IHEL,236),IHEL=1,9) / -1,  1,  1,  1, -1,  1, -1,  1,  1/
      DATA (NHEL(IHEL,237),IHEL=1,9) / -1,  1,  1,  1, -1,  1,  1, -1, -1/
      DATA (NHEL(IHEL,238),IHEL=1,9) / -1,  1,  1,  1, -1,  1,  1, -1,  1/
      DATA (NHEL(IHEL,239),IHEL=1,9) / -1,  1,  1,  1, -1,  1,  1,  1, -1/
      DATA (NHEL(IHEL,240),IHEL=1,9) / -1,  1,  1,  1, -1,  1,  1,  1,  1/
      DATA (NHEL(IHEL,241),IHEL=1,9) / -1,  1,  1,  1,  1, -1, -1, -1, -1/
      DATA (NHEL(IHEL,242),IHEL=1,9) / -1,  1,  1,  1,  1, -1, -1, -1,  1/
      DATA (NHEL(IHEL,243),IHEL=1,9) / -1,  1,  1,  1,  1, -1, -1,  1, -1/
      DATA (NHEL(IHEL,244),IHEL=1,9) / -1,  1,  1,  1,  1, -1, -1,  1,  1/
      DATA (NHEL(IHEL,245),IHEL=1,9) / -1,  1,  1,  1,  1, -1,  1, -1, -1/
      DATA (NHEL(IHEL,246),IHEL=1,9) / -1,  1,  1,  1,  1, -1,  1, -1,  1/
      DATA (NHEL(IHEL,247),IHEL=1,9) / -1,  1,  1,  1,  1, -1,  1,  1, -1/
      DATA (NHEL(IHEL,248),IHEL=1,9) / -1,  1,  1,  1,  1, -1,  1,  1,  1/
      DATA (NHEL(IHEL,249),IHEL=1,9) / -1,  1,  1,  1,  1,  1, -1, -1, -1/
      DATA (NHEL(IHEL,250),IHEL=1,9) / -1,  1,  1,  1,  1,  1, -1, -1,  1/
      DATA (NHEL(IHEL,251),IHEL=1,9) / -1,  1,  1,  1,  1,  1, -1,  1, -1/
      DATA (NHEL(IHEL,252),IHEL=1,9) / -1,  1,  1,  1,  1,  1, -1,  1,  1/
      DATA (NHEL(IHEL,253),IHEL=1,9) / -1,  1,  1,  1,  1,  1,  1, -1, -1/
      DATA (NHEL(IHEL,254),IHEL=1,9) / -1,  1,  1,  1,  1,  1,  1, -1,  1/
      DATA (NHEL(IHEL,255),IHEL=1,9) / -1,  1,  1,  1,  1,  1,  1,  1, -1/
      DATA (NHEL(IHEL,256),IHEL=1,9) / -1,  1,  1,  1,  1,  1,  1,  1,  1/
      DATA (NHEL(IHEL,257),IHEL=1,9) /  1, -1, -1, -1, -1, -1, -1, -1, -1/
      DATA (NHEL(IHEL,258),IHEL=1,9) /  1, -1, -1, -1, -1, -1, -1, -1,  1/
      DATA (NHEL(IHEL,259),IHEL=1,9) /  1, -1, -1, -1, -1, -1, -1,  1, -1/
      DATA (NHEL(IHEL,260),IHEL=1,9) /  1, -1, -1, -1, -1, -1, -1,  1,  1/
      DATA (NHEL(IHEL,261),IHEL=1,9) /  1, -1, -1, -1, -1, -1,  1, -1, -1/
      DATA (NHEL(IHEL,262),IHEL=1,9) /  1, -1, -1, -1, -1, -1,  1, -1,  1/
      DATA (NHEL(IHEL,263),IHEL=1,9) /  1, -1, -1, -1, -1, -1,  1,  1, -1/
      DATA (NHEL(IHEL,264),IHEL=1,9) /  1, -1, -1, -1, -1, -1,  1,  1,  1/
      DATA (NHEL(IHEL,265),IHEL=1,9) /  1, -1, -1, -1, -1,  1, -1, -1, -1/
      DATA (NHEL(IHEL,266),IHEL=1,9) /  1, -1, -1, -1, -1,  1, -1, -1,  1/
      DATA (NHEL(IHEL,267),IHEL=1,9) /  1, -1, -1, -1, -1,  1, -1,  1, -1/
      DATA (NHEL(IHEL,268),IHEL=1,9) /  1, -1, -1, -1, -1,  1, -1,  1,  1/
      DATA (NHEL(IHEL,269),IHEL=1,9) /  1, -1, -1, -1, -1,  1,  1, -1, -1/
      DATA (NHEL(IHEL,270),IHEL=1,9) /  1, -1, -1, -1, -1,  1,  1, -1,  1/
      DATA (NHEL(IHEL,271),IHEL=1,9) /  1, -1, -1, -1, -1,  1,  1,  1, -1/
      DATA (NHEL(IHEL,272),IHEL=1,9) /  1, -1, -1, -1, -1,  1,  1,  1,  1/
      DATA (NHEL(IHEL,273),IHEL=1,9) /  1, -1, -1, -1,  1, -1, -1, -1, -1/
      DATA (NHEL(IHEL,274),IHEL=1,9) /  1, -1, -1, -1,  1, -1, -1, -1,  1/
      DATA (NHEL(IHEL,275),IHEL=1,9) /  1, -1, -1, -1,  1, -1, -1,  1, -1/
      DATA (NHEL(IHEL,276),IHEL=1,9) /  1, -1, -1, -1,  1, -1, -1,  1,  1/
      DATA (NHEL(IHEL,277),IHEL=1,9) /  1, -1, -1, -1,  1, -1,  1, -1, -1/
      DATA (NHEL(IHEL,278),IHEL=1,9) /  1, -1, -1, -1,  1, -1,  1, -1,  1/
      DATA (NHEL(IHEL,279),IHEL=1,9) /  1, -1, -1, -1,  1, -1,  1,  1, -1/
      DATA (NHEL(IHEL,280),IHEL=1,9) /  1, -1, -1, -1,  1, -1,  1,  1,  1/
      DATA (NHEL(IHEL,281),IHEL=1,9) /  1, -1, -1, -1,  1,  1, -1, -1, -1/
      DATA (NHEL(IHEL,282),IHEL=1,9) /  1, -1, -1, -1,  1,  1, -1, -1,  1/
      DATA (NHEL(IHEL,283),IHEL=1,9) /  1, -1, -1, -1,  1,  1, -1,  1, -1/
      DATA (NHEL(IHEL,284),IHEL=1,9) /  1, -1, -1, -1,  1,  1, -1,  1,  1/
      DATA (NHEL(IHEL,285),IHEL=1,9) /  1, -1, -1, -1,  1,  1,  1, -1, -1/
      DATA (NHEL(IHEL,286),IHEL=1,9) /  1, -1, -1, -1,  1,  1,  1, -1,  1/
      DATA (NHEL(IHEL,287),IHEL=1,9) /  1, -1, -1, -1,  1,  1,  1,  1, -1/
      DATA (NHEL(IHEL,288),IHEL=1,9) /  1, -1, -1, -1,  1,  1,  1,  1,  1/
      DATA (NHEL(IHEL,289),IHEL=1,9) /  1, -1, -1,  1, -1, -1, -1, -1, -1/
      DATA (NHEL(IHEL,290),IHEL=1,9) /  1, -1, -1,  1, -1, -1, -1, -1,  1/
      DATA (NHEL(IHEL,291),IHEL=1,9) /  1, -1, -1,  1, -1, -1, -1,  1, -1/
      DATA (NHEL(IHEL,292),IHEL=1,9) /  1, -1, -1,  1, -1, -1, -1,  1,  1/
      DATA (NHEL(IHEL,293),IHEL=1,9) /  1, -1, -1,  1, -1, -1,  1, -1, -1/
      DATA (NHEL(IHEL,294),IHEL=1,9) /  1, -1, -1,  1, -1, -1,  1, -1,  1/
      DATA (NHEL(IHEL,295),IHEL=1,9) /  1, -1, -1,  1, -1, -1,  1,  1, -1/
      DATA (NHEL(IHEL,296),IHEL=1,9) /  1, -1, -1,  1, -1, -1,  1,  1,  1/
      DATA (NHEL(IHEL,297),IHEL=1,9) /  1, -1, -1,  1, -1,  1, -1, -1, -1/
      DATA (NHEL(IHEL,298),IHEL=1,9) /  1, -1, -1,  1, -1,  1, -1, -1,  1/
      DATA (NHEL(IHEL,299),IHEL=1,9) /  1, -1, -1,  1, -1,  1, -1,  1, -1/
      DATA (NHEL(IHEL,300),IHEL=1,9) /  1, -1, -1,  1, -1,  1, -1,  1,  1/
      DATA (NHEL(IHEL,301),IHEL=1,9) /  1, -1, -1,  1, -1,  1,  1, -1, -1/
      DATA (NHEL(IHEL,302),IHEL=1,9) /  1, -1, -1,  1, -1,  1,  1, -1,  1/
      DATA (NHEL(IHEL,303),IHEL=1,9) /  1, -1, -1,  1, -1,  1,  1,  1, -1/
      DATA (NHEL(IHEL,304),IHEL=1,9) /  1, -1, -1,  1, -1,  1,  1,  1,  1/
      DATA (NHEL(IHEL,305),IHEL=1,9) /  1, -1, -1,  1,  1, -1, -1, -1, -1/
      DATA (NHEL(IHEL,306),IHEL=1,9) /  1, -1, -1,  1,  1, -1, -1, -1,  1/
      DATA (NHEL(IHEL,307),IHEL=1,9) /  1, -1, -1,  1,  1, -1, -1,  1, -1/
      DATA (NHEL(IHEL,308),IHEL=1,9) /  1, -1, -1,  1,  1, -1, -1,  1,  1/
      DATA (NHEL(IHEL,309),IHEL=1,9) /  1, -1, -1,  1,  1, -1,  1, -1, -1/
      DATA (NHEL(IHEL,310),IHEL=1,9) /  1, -1, -1,  1,  1, -1,  1, -1,  1/
      DATA (NHEL(IHEL,311),IHEL=1,9) /  1, -1, -1,  1,  1, -1,  1,  1, -1/
      DATA (NHEL(IHEL,312),IHEL=1,9) /  1, -1, -1,  1,  1, -1,  1,  1,  1/
      DATA (NHEL(IHEL,313),IHEL=1,9) /  1, -1, -1,  1,  1,  1, -1, -1, -1/
      DATA (NHEL(IHEL,314),IHEL=1,9) /  1, -1, -1,  1,  1,  1, -1, -1,  1/
      DATA (NHEL(IHEL,315),IHEL=1,9) /  1, -1, -1,  1,  1,  1, -1,  1, -1/
      DATA (NHEL(IHEL,316),IHEL=1,9) /  1, -1, -1,  1,  1,  1, -1,  1,  1/
      DATA (NHEL(IHEL,317),IHEL=1,9) /  1, -1, -1,  1,  1,  1,  1, -1, -1/
      DATA (NHEL(IHEL,318),IHEL=1,9) /  1, -1, -1,  1,  1,  1,  1, -1,  1/
      DATA (NHEL(IHEL,319),IHEL=1,9) /  1, -1, -1,  1,  1,  1,  1,  1, -1/
      DATA (NHEL(IHEL,320),IHEL=1,9) /  1, -1, -1,  1,  1,  1,  1,  1,  1/
      DATA (NHEL(IHEL,321),IHEL=1,9) /  1, -1,  1, -1, -1, -1, -1, -1, -1/
      DATA (NHEL(IHEL,322),IHEL=1,9) /  1, -1,  1, -1, -1, -1, -1, -1,  1/
      DATA (NHEL(IHEL,323),IHEL=1,9) /  1, -1,  1, -1, -1, -1, -1,  1, -1/
      DATA (NHEL(IHEL,324),IHEL=1,9) /  1, -1,  1, -1, -1, -1, -1,  1,  1/
      DATA (NHEL(IHEL,325),IHEL=1,9) /  1, -1,  1, -1, -1, -1,  1, -1, -1/
      DATA (NHEL(IHEL,326),IHEL=1,9) /  1, -1,  1, -1, -1, -1,  1, -1,  1/
      DATA (NHEL(IHEL,327),IHEL=1,9) /  1, -1,  1, -1, -1, -1,  1,  1, -1/
      DATA (NHEL(IHEL,328),IHEL=1,9) /  1, -1,  1, -1, -1, -1,  1,  1,  1/
      DATA (NHEL(IHEL,329),IHEL=1,9) /  1, -1,  1, -1, -1,  1, -1, -1, -1/
      DATA (NHEL(IHEL,330),IHEL=1,9) /  1, -1,  1, -1, -1,  1, -1, -1,  1/
      DATA (NHEL(IHEL,331),IHEL=1,9) /  1, -1,  1, -1, -1,  1, -1,  1, -1/
      DATA (NHEL(IHEL,332),IHEL=1,9) /  1, -1,  1, -1, -1,  1, -1,  1,  1/
      DATA (NHEL(IHEL,333),IHEL=1,9) /  1, -1,  1, -1, -1,  1,  1, -1, -1/
      DATA (NHEL(IHEL,334),IHEL=1,9) /  1, -1,  1, -1, -1,  1,  1, -1,  1/
      DATA (NHEL(IHEL,335),IHEL=1,9) /  1, -1,  1, -1, -1,  1,  1,  1, -1/
      DATA (NHEL(IHEL,336),IHEL=1,9) /  1, -1,  1, -1, -1,  1,  1,  1,  1/
      DATA (NHEL(IHEL,337),IHEL=1,9) /  1, -1,  1, -1,  1, -1, -1, -1, -1/
      DATA (NHEL(IHEL,338),IHEL=1,9) /  1, -1,  1, -1,  1, -1, -1, -1,  1/
      DATA (NHEL(IHEL,339),IHEL=1,9) /  1, -1,  1, -1,  1, -1, -1,  1, -1/
      DATA (NHEL(IHEL,340),IHEL=1,9) /  1, -1,  1, -1,  1, -1, -1,  1,  1/
      DATA (NHEL(IHEL,341),IHEL=1,9) /  1, -1,  1, -1,  1, -1,  1, -1, -1/
      DATA (NHEL(IHEL,342),IHEL=1,9) /  1, -1,  1, -1,  1, -1,  1, -1,  1/
      DATA (NHEL(IHEL,343),IHEL=1,9) /  1, -1,  1, -1,  1, -1,  1,  1, -1/
      DATA (NHEL(IHEL,344),IHEL=1,9) /  1, -1,  1, -1,  1, -1,  1,  1,  1/
      DATA (NHEL(IHEL,345),IHEL=1,9) /  1, -1,  1, -1,  1,  1, -1, -1, -1/
      DATA (NHEL(IHEL,346),IHEL=1,9) /  1, -1,  1, -1,  1,  1, -1, -1,  1/
      DATA (NHEL(IHEL,347),IHEL=1,9) /  1, -1,  1, -1,  1,  1, -1,  1, -1/
      DATA (NHEL(IHEL,348),IHEL=1,9) /  1, -1,  1, -1,  1,  1, -1,  1,  1/
      DATA (NHEL(IHEL,349),IHEL=1,9) /  1, -1,  1, -1,  1,  1,  1, -1, -1/
      DATA (NHEL(IHEL,350),IHEL=1,9) /  1, -1,  1, -1,  1,  1,  1, -1,  1/
      DATA (NHEL(IHEL,351),IHEL=1,9) /  1, -1,  1, -1,  1,  1,  1,  1, -1/
      DATA (NHEL(IHEL,352),IHEL=1,9) /  1, -1,  1, -1,  1,  1,  1,  1,  1/
      DATA (NHEL(IHEL,353),IHEL=1,9) /  1, -1,  1,  1, -1, -1, -1, -1, -1/
      DATA (NHEL(IHEL,354),IHEL=1,9) /  1, -1,  1,  1, -1, -1, -1, -1,  1/
      DATA (NHEL(IHEL,355),IHEL=1,9) /  1, -1,  1,  1, -1, -1, -1,  1, -1/
      DATA (NHEL(IHEL,356),IHEL=1,9) /  1, -1,  1,  1, -1, -1, -1,  1,  1/
      DATA (NHEL(IHEL,357),IHEL=1,9) /  1, -1,  1,  1, -1, -1,  1, -1, -1/
      DATA (NHEL(IHEL,358),IHEL=1,9) /  1, -1,  1,  1, -1, -1,  1, -1,  1/
      DATA (NHEL(IHEL,359),IHEL=1,9) /  1, -1,  1,  1, -1, -1,  1,  1, -1/
      DATA (NHEL(IHEL,360),IHEL=1,9) /  1, -1,  1,  1, -1, -1,  1,  1,  1/
      DATA (NHEL(IHEL,361),IHEL=1,9) /  1, -1,  1,  1, -1,  1, -1, -1, -1/
      DATA (NHEL(IHEL,362),IHEL=1,9) /  1, -1,  1,  1, -1,  1, -1, -1,  1/
      DATA (NHEL(IHEL,363),IHEL=1,9) /  1, -1,  1,  1, -1,  1, -1,  1, -1/
      DATA (NHEL(IHEL,364),IHEL=1,9) /  1, -1,  1,  1, -1,  1, -1,  1,  1/
      DATA (NHEL(IHEL,365),IHEL=1,9) /  1, -1,  1,  1, -1,  1,  1, -1, -1/
      DATA (NHEL(IHEL,366),IHEL=1,9) /  1, -1,  1,  1, -1,  1,  1, -1,  1/
      DATA (NHEL(IHEL,367),IHEL=1,9) /  1, -1,  1,  1, -1,  1,  1,  1, -1/
      DATA (NHEL(IHEL,368),IHEL=1,9) /  1, -1,  1,  1, -1,  1,  1,  1,  1/
      DATA (NHEL(IHEL,369),IHEL=1,9) /  1, -1,  1,  1,  1, -1, -1, -1, -1/
      DATA (NHEL(IHEL,370),IHEL=1,9) /  1, -1,  1,  1,  1, -1, -1, -1,  1/
      DATA (NHEL(IHEL,371),IHEL=1,9) /  1, -1,  1,  1,  1, -1, -1,  1, -1/
      DATA (NHEL(IHEL,372),IHEL=1,9) /  1, -1,  1,  1,  1, -1, -1,  1,  1/
      DATA (NHEL(IHEL,373),IHEL=1,9) /  1, -1,  1,  1,  1, -1,  1, -1, -1/
      DATA (NHEL(IHEL,374),IHEL=1,9) /  1, -1,  1,  1,  1, -1,  1, -1,  1/
      DATA (NHEL(IHEL,375),IHEL=1,9) /  1, -1,  1,  1,  1, -1,  1,  1, -1/
      DATA (NHEL(IHEL,376),IHEL=1,9) /  1, -1,  1,  1,  1, -1,  1,  1,  1/
      DATA (NHEL(IHEL,377),IHEL=1,9) /  1, -1,  1,  1,  1,  1, -1, -1, -1/
      DATA (NHEL(IHEL,378),IHEL=1,9) /  1, -1,  1,  1,  1,  1, -1, -1,  1/
      DATA (NHEL(IHEL,379),IHEL=1,9) /  1, -1,  1,  1,  1,  1, -1,  1, -1/
      DATA (NHEL(IHEL,380),IHEL=1,9) /  1, -1,  1,  1,  1,  1, -1,  1,  1/
      DATA (NHEL(IHEL,381),IHEL=1,9) /  1, -1,  1,  1,  1,  1,  1, -1, -1/
      DATA (NHEL(IHEL,382),IHEL=1,9) /  1, -1,  1,  1,  1,  1,  1, -1,  1/
      DATA (NHEL(IHEL,383),IHEL=1,9) /  1, -1,  1,  1,  1,  1,  1,  1, -1/
      DATA (NHEL(IHEL,384),IHEL=1,9) /  1, -1,  1,  1,  1,  1,  1,  1,  1/
      DATA (NHEL(IHEL,385),IHEL=1,9) /  1,  1, -1, -1, -1, -1, -1, -1, -1/
      DATA (NHEL(IHEL,386),IHEL=1,9) /  1,  1, -1, -1, -1, -1, -1, -1,  1/
      DATA (NHEL(IHEL,387),IHEL=1,9) /  1,  1, -1, -1, -1, -1, -1,  1, -1/
      DATA (NHEL(IHEL,388),IHEL=1,9) /  1,  1, -1, -1, -1, -1, -1,  1,  1/
      DATA (NHEL(IHEL,389),IHEL=1,9) /  1,  1, -1, -1, -1, -1,  1, -1, -1/
      DATA (NHEL(IHEL,390),IHEL=1,9) /  1,  1, -1, -1, -1, -1,  1, -1,  1/
      DATA (NHEL(IHEL,391),IHEL=1,9) /  1,  1, -1, -1, -1, -1,  1,  1, -1/
      DATA (NHEL(IHEL,392),IHEL=1,9) /  1,  1, -1, -1, -1, -1,  1,  1,  1/
      DATA (NHEL(IHEL,393),IHEL=1,9) /  1,  1, -1, -1, -1,  1, -1, -1, -1/
      DATA (NHEL(IHEL,394),IHEL=1,9) /  1,  1, -1, -1, -1,  1, -1, -1,  1/
      DATA (NHEL(IHEL,395),IHEL=1,9) /  1,  1, -1, -1, -1,  1, -1,  1, -1/
      DATA (NHEL(IHEL,396),IHEL=1,9) /  1,  1, -1, -1, -1,  1, -1,  1,  1/
      DATA (NHEL(IHEL,397),IHEL=1,9) /  1,  1, -1, -1, -1,  1,  1, -1, -1/
      DATA (NHEL(IHEL,398),IHEL=1,9) /  1,  1, -1, -1, -1,  1,  1, -1,  1/
      DATA (NHEL(IHEL,399),IHEL=1,9) /  1,  1, -1, -1, -1,  1,  1,  1, -1/
      DATA (NHEL(IHEL,400),IHEL=1,9) /  1,  1, -1, -1, -1,  1,  1,  1,  1/
      DATA (NHEL(IHEL,401),IHEL=1,9) /  1,  1, -1, -1,  1, -1, -1, -1, -1/
      DATA (NHEL(IHEL,402),IHEL=1,9) /  1,  1, -1, -1,  1, -1, -1, -1,  1/
      DATA (NHEL(IHEL,403),IHEL=1,9) /  1,  1, -1, -1,  1, -1, -1,  1, -1/
      DATA (NHEL(IHEL,404),IHEL=1,9) /  1,  1, -1, -1,  1, -1, -1,  1,  1/
      DATA (NHEL(IHEL,405),IHEL=1,9) /  1,  1, -1, -1,  1, -1,  1, -1, -1/
      DATA (NHEL(IHEL,406),IHEL=1,9) /  1,  1, -1, -1,  1, -1,  1, -1,  1/
      DATA (NHEL(IHEL,407),IHEL=1,9) /  1,  1, -1, -1,  1, -1,  1,  1, -1/
      DATA (NHEL(IHEL,408),IHEL=1,9) /  1,  1, -1, -1,  1, -1,  1,  1,  1/
      DATA (NHEL(IHEL,409),IHEL=1,9) /  1,  1, -1, -1,  1,  1, -1, -1, -1/
      DATA (NHEL(IHEL,410),IHEL=1,9) /  1,  1, -1, -1,  1,  1, -1, -1,  1/
      DATA (NHEL(IHEL,411),IHEL=1,9) /  1,  1, -1, -1,  1,  1, -1,  1, -1/
      DATA (NHEL(IHEL,412),IHEL=1,9) /  1,  1, -1, -1,  1,  1, -1,  1,  1/
      DATA (NHEL(IHEL,413),IHEL=1,9) /  1,  1, -1, -1,  1,  1,  1, -1, -1/
      DATA (NHEL(IHEL,414),IHEL=1,9) /  1,  1, -1, -1,  1,  1,  1, -1,  1/
      DATA (NHEL(IHEL,415),IHEL=1,9) /  1,  1, -1, -1,  1,  1,  1,  1, -1/
      DATA (NHEL(IHEL,416),IHEL=1,9) /  1,  1, -1, -1,  1,  1,  1,  1,  1/
      DATA (NHEL(IHEL,417),IHEL=1,9) /  1,  1, -1,  1, -1, -1, -1, -1, -1/
      DATA (NHEL(IHEL,418),IHEL=1,9) /  1,  1, -1,  1, -1, -1, -1, -1,  1/
      DATA (NHEL(IHEL,419),IHEL=1,9) /  1,  1, -1,  1, -1, -1, -1,  1, -1/
      DATA (NHEL(IHEL,420),IHEL=1,9) /  1,  1, -1,  1, -1, -1, -1,  1,  1/
      DATA (NHEL(IHEL,421),IHEL=1,9) /  1,  1, -1,  1, -1, -1,  1, -1, -1/
      DATA (NHEL(IHEL,422),IHEL=1,9) /  1,  1, -1,  1, -1, -1,  1, -1,  1/
      DATA (NHEL(IHEL,423),IHEL=1,9) /  1,  1, -1,  1, -1, -1,  1,  1, -1/
      DATA (NHEL(IHEL,424),IHEL=1,9) /  1,  1, -1,  1, -1, -1,  1,  1,  1/
      DATA (NHEL(IHEL,425),IHEL=1,9) /  1,  1, -1,  1, -1,  1, -1, -1, -1/
      DATA (NHEL(IHEL,426),IHEL=1,9) /  1,  1, -1,  1, -1,  1, -1, -1,  1/
      DATA (NHEL(IHEL,427),IHEL=1,9) /  1,  1, -1,  1, -1,  1, -1,  1, -1/
      DATA (NHEL(IHEL,428),IHEL=1,9) /  1,  1, -1,  1, -1,  1, -1,  1,  1/
      DATA (NHEL(IHEL,429),IHEL=1,9) /  1,  1, -1,  1, -1,  1,  1, -1, -1/
      DATA (NHEL(IHEL,430),IHEL=1,9) /  1,  1, -1,  1, -1,  1,  1, -1,  1/
      DATA (NHEL(IHEL,431),IHEL=1,9) /  1,  1, -1,  1, -1,  1,  1,  1, -1/
      DATA (NHEL(IHEL,432),IHEL=1,9) /  1,  1, -1,  1, -1,  1,  1,  1,  1/
      DATA (NHEL(IHEL,433),IHEL=1,9) /  1,  1, -1,  1,  1, -1, -1, -1, -1/
      DATA (NHEL(IHEL,434),IHEL=1,9) /  1,  1, -1,  1,  1, -1, -1, -1,  1/
      DATA (NHEL(IHEL,435),IHEL=1,9) /  1,  1, -1,  1,  1, -1, -1,  1, -1/
      DATA (NHEL(IHEL,436),IHEL=1,9) /  1,  1, -1,  1,  1, -1, -1,  1,  1/
      DATA (NHEL(IHEL,437),IHEL=1,9) /  1,  1, -1,  1,  1, -1,  1, -1, -1/
      DATA (NHEL(IHEL,438),IHEL=1,9) /  1,  1, -1,  1,  1, -1,  1, -1,  1/
      DATA (NHEL(IHEL,439),IHEL=1,9) /  1,  1, -1,  1,  1, -1,  1,  1, -1/
      DATA (NHEL(IHEL,440),IHEL=1,9) /  1,  1, -1,  1,  1, -1,  1,  1,  1/
      DATA (NHEL(IHEL,441),IHEL=1,9) /  1,  1, -1,  1,  1,  1, -1, -1, -1/
      DATA (NHEL(IHEL,442),IHEL=1,9) /  1,  1, -1,  1,  1,  1, -1, -1,  1/
      DATA (NHEL(IHEL,443),IHEL=1,9) /  1,  1, -1,  1,  1,  1, -1,  1, -1/
      DATA (NHEL(IHEL,444),IHEL=1,9) /  1,  1, -1,  1,  1,  1, -1,  1,  1/
      DATA (NHEL(IHEL,445),IHEL=1,9) /  1,  1, -1,  1,  1,  1,  1, -1, -1/
      DATA (NHEL(IHEL,446),IHEL=1,9) /  1,  1, -1,  1,  1,  1,  1, -1,  1/
      DATA (NHEL(IHEL,447),IHEL=1,9) /  1,  1, -1,  1,  1,  1,  1,  1, -1/
      DATA (NHEL(IHEL,448),IHEL=1,9) /  1,  1, -1,  1,  1,  1,  1,  1,  1/
      DATA (NHEL(IHEL,449),IHEL=1,9) /  1,  1,  1, -1, -1, -1, -1, -1, -1/
      DATA (NHEL(IHEL,450),IHEL=1,9) /  1,  1,  1, -1, -1, -1, -1, -1,  1/
      DATA (NHEL(IHEL,451),IHEL=1,9) /  1,  1,  1, -1, -1, -1, -1,  1, -1/
      DATA (NHEL(IHEL,452),IHEL=1,9) /  1,  1,  1, -1, -1, -1, -1,  1,  1/
      DATA (NHEL(IHEL,453),IHEL=1,9) /  1,  1,  1, -1, -1, -1,  1, -1, -1/
      DATA (NHEL(IHEL,454),IHEL=1,9) /  1,  1,  1, -1, -1, -1,  1, -1,  1/
      DATA (NHEL(IHEL,455),IHEL=1,9) /  1,  1,  1, -1, -1, -1,  1,  1, -1/
      DATA (NHEL(IHEL,456),IHEL=1,9) /  1,  1,  1, -1, -1, -1,  1,  1,  1/
      DATA (NHEL(IHEL,457),IHEL=1,9) /  1,  1,  1, -1, -1,  1, -1, -1, -1/
      DATA (NHEL(IHEL,458),IHEL=1,9) /  1,  1,  1, -1, -1,  1, -1, -1,  1/
      DATA (NHEL(IHEL,459),IHEL=1,9) /  1,  1,  1, -1, -1,  1, -1,  1, -1/
      DATA (NHEL(IHEL,460),IHEL=1,9) /  1,  1,  1, -1, -1,  1, -1,  1,  1/
      DATA (NHEL(IHEL,461),IHEL=1,9) /  1,  1,  1, -1, -1,  1,  1, -1, -1/
      DATA (NHEL(IHEL,462),IHEL=1,9) /  1,  1,  1, -1, -1,  1,  1, -1,  1/
      DATA (NHEL(IHEL,463),IHEL=1,9) /  1,  1,  1, -1, -1,  1,  1,  1, -1/
      DATA (NHEL(IHEL,464),IHEL=1,9) /  1,  1,  1, -1, -1,  1,  1,  1,  1/
      DATA (NHEL(IHEL,465),IHEL=1,9) /  1,  1,  1, -1,  1, -1, -1, -1, -1/
      DATA (NHEL(IHEL,466),IHEL=1,9) /  1,  1,  1, -1,  1, -1, -1, -1,  1/
      DATA (NHEL(IHEL,467),IHEL=1,9) /  1,  1,  1, -1,  1, -1, -1,  1, -1/
      DATA (NHEL(IHEL,468),IHEL=1,9) /  1,  1,  1, -1,  1, -1, -1,  1,  1/
      DATA (NHEL(IHEL,469),IHEL=1,9) /  1,  1,  1, -1,  1, -1,  1, -1, -1/
      DATA (NHEL(IHEL,470),IHEL=1,9) /  1,  1,  1, -1,  1, -1,  1, -1,  1/
      DATA (NHEL(IHEL,471),IHEL=1,9) /  1,  1,  1, -1,  1, -1,  1,  1, -1/
      DATA (NHEL(IHEL,472),IHEL=1,9) /  1,  1,  1, -1,  1, -1,  1,  1,  1/
      DATA (NHEL(IHEL,473),IHEL=1,9) /  1,  1,  1, -1,  1,  1, -1, -1, -1/
      DATA (NHEL(IHEL,474),IHEL=1,9) /  1,  1,  1, -1,  1,  1, -1, -1,  1/
      DATA (NHEL(IHEL,475),IHEL=1,9) /  1,  1,  1, -1,  1,  1, -1,  1, -1/
      DATA (NHEL(IHEL,476),IHEL=1,9) /  1,  1,  1, -1,  1,  1, -1,  1,  1/
      DATA (NHEL(IHEL,477),IHEL=1,9) /  1,  1,  1, -1,  1,  1,  1, -1, -1/
      DATA (NHEL(IHEL,478),IHEL=1,9) /  1,  1,  1, -1,  1,  1,  1, -1,  1/
      DATA (NHEL(IHEL,479),IHEL=1,9) /  1,  1,  1, -1,  1,  1,  1,  1, -1/
      DATA (NHEL(IHEL,480),IHEL=1,9) /  1,  1,  1, -1,  1,  1,  1,  1,  1/
      DATA (NHEL(IHEL,481),IHEL=1,9) /  1,  1,  1,  1, -1, -1, -1, -1, -1/
      DATA (NHEL(IHEL,482),IHEL=1,9) /  1,  1,  1,  1, -1, -1, -1, -1,  1/
      DATA (NHEL(IHEL,483),IHEL=1,9) /  1,  1,  1,  1, -1, -1, -1,  1, -1/
      DATA (NHEL(IHEL,484),IHEL=1,9) /  1,  1,  1,  1, -1, -1, -1,  1,  1/
      DATA (NHEL(IHEL,485),IHEL=1,9) /  1,  1,  1,  1, -1, -1,  1, -1, -1/
      DATA (NHEL(IHEL,486),IHEL=1,9) /  1,  1,  1,  1, -1, -1,  1, -1,  1/
      DATA (NHEL(IHEL,487),IHEL=1,9) /  1,  1,  1,  1, -1, -1,  1,  1, -1/
      DATA (NHEL(IHEL,488),IHEL=1,9) /  1,  1,  1,  1, -1, -1,  1,  1,  1/
      DATA (NHEL(IHEL,489),IHEL=1,9) /  1,  1,  1,  1, -1,  1, -1, -1, -1/
      DATA (NHEL(IHEL,490),IHEL=1,9) /  1,  1,  1,  1, -1,  1, -1, -1,  1/
      DATA (NHEL(IHEL,491),IHEL=1,9) /  1,  1,  1,  1, -1,  1, -1,  1, -1/
      DATA (NHEL(IHEL,492),IHEL=1,9) /  1,  1,  1,  1, -1,  1, -1,  1,  1/
      DATA (NHEL(IHEL,493),IHEL=1,9) /  1,  1,  1,  1, -1,  1,  1, -1, -1/
      DATA (NHEL(IHEL,494),IHEL=1,9) /  1,  1,  1,  1, -1,  1,  1, -1,  1/
      DATA (NHEL(IHEL,495),IHEL=1,9) /  1,  1,  1,  1, -1,  1,  1,  1, -1/
      DATA (NHEL(IHEL,496),IHEL=1,9) /  1,  1,  1,  1, -1,  1,  1,  1,  1/
      DATA (NHEL(IHEL,497),IHEL=1,9) /  1,  1,  1,  1,  1, -1, -1, -1, -1/
      DATA (NHEL(IHEL,498),IHEL=1,9) /  1,  1,  1,  1,  1, -1, -1, -1,  1/
      DATA (NHEL(IHEL,499),IHEL=1,9) /  1,  1,  1,  1,  1, -1, -1,  1, -1/
      DATA (NHEL(IHEL,500),IHEL=1,9) /  1,  1,  1,  1,  1, -1, -1,  1,  1/
      DATA (NHEL(IHEL,501),IHEL=1,9) /  1,  1,  1,  1,  1, -1,  1, -1, -1/
      DATA (NHEL(IHEL,502),IHEL=1,9) /  1,  1,  1,  1,  1, -1,  1, -1,  1/
      DATA (NHEL(IHEL,503),IHEL=1,9) /  1,  1,  1,  1,  1, -1,  1,  1, -1/
      DATA (NHEL(IHEL,504),IHEL=1,9) /  1,  1,  1,  1,  1, -1,  1,  1,  1/
      DATA (NHEL(IHEL,505),IHEL=1,9) /  1,  1,  1,  1,  1,  1, -1, -1, -1/
      DATA (NHEL(IHEL,506),IHEL=1,9) /  1,  1,  1,  1,  1,  1, -1, -1,  1/
      DATA (NHEL(IHEL,507),IHEL=1,9) /  1,  1,  1,  1,  1,  1, -1,  1, -1/
      DATA (NHEL(IHEL,508),IHEL=1,9) /  1,  1,  1,  1,  1,  1, -1,  1,  1/
      DATA (NHEL(IHEL,509),IHEL=1,9) /  1,  1,  1,  1,  1,  1,  1, -1, -1/
      DATA (NHEL(IHEL,510),IHEL=1,9) /  1,  1,  1,  1,  1,  1,  1, -1,  1/
      DATA (NHEL(IHEL,511),IHEL=1,9) /  1,  1,  1,  1,  1,  1,  1,  1, -1/
      DATA (NHEL(IHEL,512),IHEL=1,9) /  1,  1,  1,  1,  1,  1,  1,  1,  1/
      DATA (  IC(IHEL,  1),IHEL=1,9) /  1,  2,  3,  4,  5,  6,  7,  8,  9/
      DATA (IDEN(IHEL),IHEL=  1,  1) / 256/
C ----------
C BEGIN CODE
C ----------
      NTRY=NTRY+1
      DO IPROC=1,NCROSS
      CALL SWITCHMOM(P1,P,IC(1,IPROC),JC,NEXTERNAL)
      DO IHEL=1,NEXTERNAL
         JC(IHEL) = +1
      ENDDO
      ANS(IPROC) = 0D0
      DO IHEL=1,NCOMB
          IF (GOODHEL(IHEL,IPROC) .OR. NTRY .LT. 2) THEN
             T=GG_VEEPBBBMUMV(P ,NHEL(1,IHEL),JC(1))            
             ANS(IPROC)=ANS(IPROC)+T
              IF (T .GT. 0D0 .AND. .NOT. GOODHEL(IHEL,IPROC)) THEN
                  GOODHEL(IHEL,IPROC)=.TRUE.
C             WRITE(*,*) IHEL,T
              ENDIF
          ENDIF
      ENDDO
      ANS(IPROC)=ANS(IPROC)/DBLE(IDEN(IPROC))
      ENDDO
      END
       
       
      REAL*8 FUNCTION GG_VEEPBBBMUMV(P,NHEL,IC)
C  
C FUNCTION GENERATED BY MADGRAPH
C RETURNS AMPLITUDE SQUARED SUMMED/AVG OVER COLORS
C FOR THE POINT WITH EXTERNAL LINES W(0:6,NEXTERNAL)
C  
C FOR PROCESS : g g -> ve e+ b b~ mu- vm~ g  
C  
      IMPLICIT NONE
C  
C CONSTANTS
C  
      INTEGER    NGRAPHS,    NEIGEN,    NEXTERNAL       
      PARAMETER (NGRAPHS=  24,NEIGEN=  6,NEXTERNAL=9)   
      INTEGER    NWAVEFUNCS     , NCOLOR
      PARAMETER (NWAVEFUNCS=  57, NCOLOR=   6) 
      REAL*8     ZERO
      PARAMETER (ZERO=0D0)
C  
C ARGUMENTS 
C  
      REAL*8 P(0:3,NEXTERNAL)
      INTEGER NHEL(NEXTERNAL), IC(NEXTERNAL)
C  
C LOCAL VARIABLES 
C  
      INTEGER I,J
      COMPLEX*16 ZTEMP
      REAL*8 DENOM(NCOLOR), CF(NCOLOR,NCOLOR)
      COMPLEX*16 AMP(NGRAPHS), JAMP(NCOLOR)
      COMPLEX*16 W(6,NWAVEFUNCS),WX1(6),WX2(6)
C  
C GLOBAL VARIABLES
C  
c      REAL*8           GG(2), G
c      COMMON /COUPQCD/ GG,    G
c      REAL*8            FMASS(12), FWIDTH(12)
c      COMMON /FERMIONS/ FMASS,     FWIDTH
       include 'coupl.inc'
C  
C COLOR DATA
C  
      DATA Denom(1  )/            9/                                       
      DATA (CF(i,1  ),i=1  ,6  ) /    64,   -8,    1,    1,   10,   -8/    
C               T[5,6,2,1,9]                                               
      DATA Denom(2  )/            9/                                       
      DATA (CF(i,2  ),i=1  ,6  ) /    -8,   64,   -8,   10,    1,    1/    
C               T[5,6,2,9,1]                                               
      DATA Denom(3  )/            9/                                       
      DATA (CF(i,3  ),i=1  ,6  ) /     1,   -8,   64,    1,   -8,   10/    
C               T[5,6,9,2,1]                                               
      DATA Denom(4  )/            9/                                       
      DATA (CF(i,4  ),i=1  ,6  ) /     1,   10,    1,   64,   -8,   -8/    
C               T[5,6,1,9,2]                                               
      DATA Denom(5  )/            9/                                       
      DATA (CF(i,5  ),i=1  ,6  ) /    10,    1,   -8,   -8,   64,    1/    
C               T[5,6,9,1,2]                                               
      DATA Denom(6  )/            9/                                       
      DATA (CF(i,6  ),i=1  ,6  ) /    -8,    1,   10,   -8,    1,   64/    
C               T[5,6,1,2,9]                                               
C ----------
C BEGIN CODE
C ----------
      write(6,*) 'gg(1)',gg(1)
      write(6,*) 'gg(2)',gg(2)
      write(6,*) 'wmass',wmass
      write(6,*) 'wwidth',wwidth
      write(6,*) 'tmass',tmass
      write(6,*) 'twidth',twidth
      write(6,*) 'bmass',bmass
      write(6,*) 'gwf',gwf
      write(6,*) 'gg',gg


      CALL VXXXXX(P(0,1   ),ZERO ,NHEL(1   ),-1*IC(1   ),W(1,1   ))        
      CALL VXXXXX(P(0,2   ),ZERO ,NHEL(2   ),-1*IC(2   ),W(1,2   ))        
      CALL OXXXXX(P(0,3   ),ZERO ,NHEL(3   ),+1*IC(3   ),W(1,3   ))        
      CALL IXXXXX(P(0,4   ),ZERO ,NHEL(4   ),-1*IC(4   ),W(1,4   ))        
      CALL OXXXXX(P(0,5   ),BMASS ,NHEL(5   ),+1*IC(5   ),W(1,5   ))       
      CALL IXXXXX(P(0,6   ),BMASS ,NHEL(6   ),-1*IC(6   ),W(1,6   ))       
      CALL OXXXXX(P(0,7   ),ZERO ,NHEL(7   ),+1*IC(7   ),W(1,7   ))        
      CALL IXXXXX(P(0,8   ),ZERO ,NHEL(8   ),-1*IC(8   ),W(1,8   ))        
      CALL VXXXXX(P(0,9   ),ZERO ,NHEL(9   ),+1*IC(9   ),W(1,9   ))        
      CALL JIOXXX(W(1,4   ),W(1,3   ),GWF ,WMASS   ,WWIDTH  ,W(1,10  ))    
      CALL FVOXXX(W(1,5   ),W(1,10  ),GWF ,TMASS   ,TWIDTH  ,W(1,11  ))    
      CALL JIOXXX(W(1,8   ),W(1,7   ),GWF ,WMASS   ,WWIDTH  ,W(1,12  ))    
      CALL JVVXXX(W(1,9   ),W(1,1   ),G ,ZERO    ,ZERO    ,W(1,13  ))      
      CALL FVOXXX(W(1,11  ),W(1,2   ),GG ,TMASS   ,TWIDTH  ,W(1,14  ))     
      CALL FVOXXX(W(1,14  ),W(1,13  ),GG ,TMASS   ,TWIDTH  ,W(1,15  ))     
      CALL IOVXXX(W(1,6   ),W(1,15  ),W(1,12  ),GWF ,AMP(1   ))            
      CALL JVVXXX(W(1,9   ),W(1,2   ),G ,ZERO    ,ZERO    ,W(1,16  ))      
      CALL FVOXXX(W(1,11  ),W(1,16  ),GG ,TMASS   ,TWIDTH  ,W(1,17  ))     
      CALL FVOXXX(W(1,17  ),W(1,1   ),GG ,TMASS   ,TWIDTH  ,W(1,18  ))     
      CALL IOVXXX(W(1,6   ),W(1,18  ),W(1,12  ),GWF ,AMP(2   ))            
      CALL FVOXXX(W(1,5   ),W(1,9   ),GG ,BMASS   ,ZERO    ,W(1,19  ))     
      CALL FVOXXX(W(1,19  ),W(1,10  ),GWF ,TMASS   ,TWIDTH  ,W(1,20  ))    
      CALL FVIXXX(W(1,6   ),W(1,12  ),GWF ,TMASS   ,TWIDTH  ,W(1,21  ))    
      CALL FVOXXX(W(1,20  ),W(1,2   ),GG ,TMASS   ,TWIDTH  ,W(1,22  ))     
      CALL IOVXXX(W(1,21  ),W(1,22  ),W(1,1   ),GG ,AMP(3   ))             
      CALL FVIXXX(W(1,6   ),W(1,9   ),GG ,BMASS   ,ZERO    ,W(1,23  ))     
      CALL FVOXXX(W(1,14  ),W(1,1   ),GG ,TMASS   ,TWIDTH  ,W(1,24  ))     
      CALL IOVXXX(W(1,23  ),W(1,24  ),W(1,12  ),GWF ,AMP(4   ))            
      CALL FVOXXX(W(1,11  ),W(1,9   ),GG ,TMASS   ,TWIDTH  ,W(1,25  ))     
      CALL FVOXXX(W(1,25  ),W(1,2   ),GG ,TMASS   ,TWIDTH  ,W(1,26  ))     
      CALL FVOXXX(W(1,26  ),W(1,1   ),GG ,TMASS   ,TWIDTH  ,W(1,27  ))     
      CALL IOVXXX(W(1,6   ),W(1,27  ),W(1,12  ),GWF ,AMP(5   ))            
      CALL FVOXXX(W(1,14  ),W(1,9   ),GG ,TMASS   ,TWIDTH  ,W(1,28  ))     
      CALL IOVXXX(W(1,21  ),W(1,28  ),W(1,1   ),GG ,AMP(6   ))             
      CALL IOVXXX(W(1,21  ),W(1,24  ),W(1,9   ),GG ,AMP(7   ))             
      CALL FVOXXX(W(1,11  ),W(1,13  ),GG ,TMASS   ,TWIDTH  ,W(1,29  ))     
      CALL FVOXXX(W(1,29  ),W(1,2   ),GG ,TMASS   ,TWIDTH  ,W(1,30  ))     
      CALL IOVXXX(W(1,6   ),W(1,30  ),W(1,12  ),GWF ,AMP(8   ))            
      CALL FVOXXX(W(1,11  ),W(1,1   ),GG ,TMASS   ,TWIDTH  ,W(1,31  ))     
      CALL FVOXXX(W(1,31  ),W(1,16  ),GG ,TMASS   ,TWIDTH  ,W(1,32  ))     
      CALL IOVXXX(W(1,6   ),W(1,32  ),W(1,12  ),GWF ,AMP(9   ))            
      CALL FVOXXX(W(1,20  ),W(1,1   ),GG ,TMASS   ,TWIDTH  ,W(1,33  ))     
      CALL IOVXXX(W(1,21  ),W(1,33  ),W(1,2   ),GG ,AMP(10  ))             
      CALL FVOXXX(W(1,31  ),W(1,2   ),GG ,TMASS   ,TWIDTH  ,W(1,34  ))     
      CALL IOVXXX(W(1,23  ),W(1,34  ),W(1,12  ),GWF ,AMP(11  ))            
      CALL FVOXXX(W(1,25  ),W(1,1   ),GG ,TMASS   ,TWIDTH  ,W(1,35  ))     
      CALL FVOXXX(W(1,35  ),W(1,2   ),GG ,TMASS   ,TWIDTH  ,W(1,36  ))     
      CALL IOVXXX(W(1,6   ),W(1,36  ),W(1,12  ),GWF ,AMP(12  ))            
      CALL FVOXXX(W(1,31  ),W(1,9   ),GG ,TMASS   ,TWIDTH  ,W(1,37  ))     
      CALL IOVXXX(W(1,21  ),W(1,37  ),W(1,2   ),GG ,AMP(13  ))             
      CALL IOVXXX(W(1,21  ),W(1,34  ),W(1,9   ),GG ,AMP(14  ))             
      CALL JVVXXX(W(1,13  ),W(1,2   ),G ,ZERO    ,ZERO    ,W(1,38  ))      
      CALL FVOXXX(W(1,11  ),W(1,38  ),GG ,TMASS   ,TWIDTH  ,W(1,39  ))     
      CALL IOVXXX(W(1,6   ),W(1,39  ),W(1,12  ),GWF ,AMP(15  ))            
      CALL JVVXXX(W(1,1   ),W(1,16  ),G ,ZERO    ,ZERO    ,W(1,40  ))      
      CALL FVOXXX(W(1,11  ),W(1,40  ),GG ,TMASS   ,TWIDTH  ,W(1,41  ))     
      CALL IOVXXX(W(1,6   ),W(1,41  ),W(1,12  ),GWF ,AMP(16  ))            
      CALL JVVXXX(W(1,1   ),W(1,2   ),G ,ZERO    ,ZERO    ,W(1,42  ))      
      CALL FVOXXX(W(1,20  ),W(1,42  ),GG ,TMASS   ,TWIDTH  ,W(1,43  ))     
      CALL IOVXXX(W(1,6   ),W(1,43  ),W(1,12  ),GWF ,AMP(17  ))            
      CALL FVOXXX(W(1,11  ),W(1,42  ),GG ,TMASS   ,TWIDTH  ,W(1,44  ))     
      CALL IOVXXX(W(1,23  ),W(1,44  ),W(1,12  ),GWF ,AMP(18  ))            
      CALL FVOXXX(W(1,25  ),W(1,42  ),GG ,TMASS   ,TWIDTH  ,W(1,45  ))     
      CALL IOVXXX(W(1,6   ),W(1,45  ),W(1,12  ),GWF ,AMP(19  ))            
      CALL JVVXXX(W(1,9   ),W(1,42  ),G ,ZERO    ,ZERO    ,W(1,46  ))      
      CALL FVOXXX(W(1,11  ),W(1,46  ),GG ,TMASS   ,TWIDTH  ,W(1,47  ))     
      CALL IOVXXX(W(1,6   ),W(1,47  ),W(1,12  ),GWF ,AMP(20  ))            
      CALL FVOXXX(W(1,44  ),W(1,9   ),GG ,TMASS   ,TWIDTH  ,W(1,48  ))     
      CALL IOVXXX(W(1,6   ),W(1,48  ),W(1,12  ),GWF ,AMP(21  ))            
      CALL JGGGXX(W(1,1   ),W(1,2   ),W(1,9   ),G ,W(1,49  ))              
      CALL FVOXXX(W(1,11  ),W(1,49  ),GG ,TMASS   ,TWIDTH  ,W(1,50  ))     
      CALL JIOXXX(W(1,6   ),W(1,50  ),GWF ,WMASS   ,WWIDTH  ,W(1,51  ))    
      CALL IOVXXX(W(1,8   ),W(1,7   ),W(1,51  ),GWF ,AMP(22  ))            
      CALL JGGGXX(W(1,9   ),W(1,1   ),W(1,2   ),G ,W(1,52  ))              
      CALL FVOXXX(W(1,11  ),W(1,52  ),GG ,TMASS   ,TWIDTH  ,W(1,53  ))     
      CALL JIOXXX(W(1,6   ),W(1,53  ),GWF ,WMASS   ,WWIDTH  ,W(1,54  ))    
      CALL IOVXXX(W(1,8   ),W(1,7   ),W(1,54  ),GWF ,AMP(23  ))            
      CALL JGGGXX(W(1,2   ),W(1,9   ),W(1,1   ),G ,W(1,55  ))              
      CALL FVOXXX(W(1,11  ),W(1,55  ),GG ,TMASS   ,TWIDTH  ,W(1,56  ))     
      CALL JIOXXX(W(1,6   ),W(1,56  ),GWF ,WMASS   ,WWIDTH  ,W(1,57  ))    
      CALL IOVXXX(W(1,8   ),W(1,7   ),W(1,57  ),GWF ,AMP(24  ))            
      include 'skip.f'
      JAMP(   1) = +AMP(   1)-AMP(   4)-AMP(   7)-AMP(  15)+AMP(  18)
     &             -AMP(  20)+AMP(  21)-AMP(  22)+AMP(  23)
      JAMP(   2) = -AMP(   1)+AMP(   2)-AMP(   6)+AMP(  15)-AMP(  16)
     &             -AMP(  23)+AMP(  24)
      JAMP(   3) = -AMP(   2)-AMP(   3)-AMP(   5)+AMP(  16)+AMP(  17)
     &             +AMP(  19)+AMP(  20)+AMP(  22)-AMP(  24)
      JAMP(   4) = +AMP(   8)-AMP(   9)-AMP(  13)+AMP(  15)-AMP(  16)
     &             -AMP(  23)+AMP(  24)
      JAMP(   5) = -AMP(   8)-AMP(  10)-AMP(  12)-AMP(  15)-AMP(  17)
     &             -AMP(  19)-AMP(  20)-AMP(  22)+AMP(  23)
      JAMP(   6) = +AMP(   9)-AMP(  11)-AMP(  14)+AMP(  16)-AMP(  18)
     &             +AMP(  20)-AMP(  21)+AMP(  22)-AMP(  24)

      GG_VEEPBBBMUMV = 0.D0 
      DO I = 1, NCOLOR
          ZTEMP = (0.D0,0.D0)
          DO J = 1, NCOLOR
              ZTEMP = ZTEMP + CF(J,I)*JAMP(J)
          ENDDO
          GG_VEEPBBBMUMV =GG_VEEPBBBMUMV+ZTEMP*DCONJG(JAMP(I))/DENOM(I)   
      ENDDO
C      CALL GAUGECHECK(JAMP,ZTEMP,EIGEN_VEC,EIGEN_VAL,NCOLOR,NEIGEN) 
      END
